apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendify-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  # 1. Match the labels on your Kubernetes Service
  selector:
    matchLabels:
      app: trendstore
  # 2. Tell Prometheus to look in the application's namespace
  namespaceSelector:
    matchNames:
      - trendstore
  endpoints:
    # 3. Must match the name of the port in your Service YAML
    - port: http 
      path: /metrics
      interval: 15s