apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendify-monitor
  namespace: monitoring
  labels:
    # This label is critical: it tells the Prometheus Operator to pick up this configuration
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      # Match the labels of your Trendify Kubernetes Service
      app: trendstore
  endpoints:
    - port: http # Must match the port name defined in your Trendify Service
      path: /metrics
      interval: 15s