# monitoring/custom-values.yaml

grafana:
  adminPassword: "trendify-admin" # Change this later
  
  # Expose Grafana using the AWS Load Balancer Controller
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
      alb.ingress.kubernetes.io/load-balancer-name: monitoring-alb
      # COMMENT OUT OR REMOVE THESE:
      # alb.ingress.kubernetes.io/ssl-redirect: '443'
      # alb.ingress.kubernetes.io/certificate-arn: ...
    # Completely remove or comment out the `hosts:` block 
    # so Helm uses the default wildcard routing
    # hosts:
    #  - ""
    hosts:
      - "" # Leaving empty creates a wildcard ALB route for testing
      
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
          # EKS default storage class
          storageClassName: gp2 

prometheus-blackbox-exporter:
  enabled: true
  serviceMonitor:
    enabled: true

defaultRules:
  create: true
  rules:
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false